biodividx:
  image: diogok/lein
  links:
    - elasticsearch:elasticsearch
    - taxadata:taxadata
    - dwcbot:dwcbot
    - dwc:dwc
  volumes:
    - .:/project
    - ~/.m2:/m2
taxadata:
  image: diogok/taxadata
  ports:
    - 8080:80
dwc:
  image: diogok/dwc-services
  ports:
    - 8484:80
dwcbot:
  image: diogok/dwc-bot
  ports:
    - 8383:8383
  volumes:
    - /var/data/dwc-bot:/var/data/dwc-bot:rw
elasticsearch:
  image: diogok/elasticsearch
  ports:
    - 9200:9200
  volumes:
    - /var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw
kibana:
  image: diogok/kibana
  ports:
    - 8282:8001
  links:
    - elasticsearch:elasticsearch
